plugins {
    id 'java'
}

group = 'org.springframework'
version = '5.3.5'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    optional(project(":spring-context"))
}

test {
    useJUnitPlatform()
}