plugins {
    id 'java'
}

group = 'icu.zhaocc'
version = '6.2.20-SNAPSHOT'

repositories {
    mavenLocal()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    api(project(":spring-context"))

}

test {
    useJUnitPlatform()
}